"""Added shit

Revision ID: a918d703b577
Revises: ae19f3588198
Create Date: 2022-07-21 15:57:04.056440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a918d703b577'
down_revision = 'ae19f3588198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_column', sa.Column('filled_cells', sa.Integer(), nullable=True))
    op.drop_column('storage_column', 'nb_tools')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_column', sa.Column('nb_tools', sa.INTEGER(), nullable=True))
    op.drop_column('storage_column', 'filled_cells')
    # ### end Alembic commands ###
