"""Initial migration.

Revision ID: ae19f3588198
Revises: 
Create Date: 2022-07-20 14:29:15.255271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae19f3588198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('spatula', sa.Integer(), nullable=True))
    op.drop_column('template', 'spetula')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('spetula', sa.INTEGER(), nullable=True))
    op.drop_column('template', 'spatula')
    # ### end Alembic commands ###
